<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    


    <script>
    

        // console.log("start");

        // const serverStatus = false;
        // const login =(username , password ,succcessFn ,errorFn) =>{
        //     setTimeout( () =>{
        //         if(serverStatus){
        //             succcessFn ({username : username , email : "info@sadikturan.com"})

        //         }else{
        //             errorFn("server kapalı");
        //         }
        //     },1000);
        // }

        // const getPostsByUsername = (username ,succcessFn) => {
        //     setTimeout(()=> {
        //         succcessFn(["post 1" ,"post 2","post 3"]);
        //     },2000); 
        // }


        // const getPostsDetails = (post , callback) =>{
        //     setTimeout(()=>{
        //         callback("post details");
        //     },1000);
        // }


        // //iç içe çalışma callback hell

        // login("sadikturan","12345",user =>{
        //     console.log(user);
        //     console.log(user.username);
        //     console.log(user.email);

        //     getPostsByUsername(user.username ,(posts)=>{
        //         console.log(posts);

        //         getPostsDetails(posts[0],(details)=>{
        //             console.log(details);
        //         });
        //     });

        // }, (error) => {
        //     console.log(error);

        // });

        
        
        // //iç içe süreçlerden doğan callback hell oluşabilir

        // console.log("end");

            //const serverStatus = true;
            const serverStatus = false;
            
            const promise = new Promise((resolve,reject)=> {
                setTimeout(()=>{
                    if(serverStatus){
                        resolve({username : "sadikturan"});
                    }else{
                        reject("login error");
                    }
                },2000);
            });

            promise.then(user => {
                console.log(user);
            }).catch(err =>{
                console.log(err);
            });



    </script>
</body>
</html>